### ISSUE TITLE
Syllables

### ISSUE THREAD

**Issue by vin-ni** [nlp-compromise/de-compromise#13]
Does it also return syllables?
Couldn't find anything in the code.

Thanks :)

**Comment by spencermountain** [comment]
hi Vinzenz, sorry no it doesn't.
early versions of English-compromise did syllables, but it no-longer does that either.
the old code is available [here](https://github.com/nlp-compromise/nlp-syllables), but german would required different rules
cheers

**Comment by BennyAlex** [comment]
@spencermountain 
On the english readme it still shows this
![image](https://github.com/nlp-compromise/de-compromise/assets/17402724/ea0f9e8f-38cd-4ef2-8dc9-67ec619ae0f4)

Is this now possible also for german or not?

thanks!

**Comment by spencermountain** [comment]
Hey @BennyAlex agh cool idea. I never thought about this.

Short answer is no, medium answer is well maybe?? Long answer is that we should definitely build it, if it cant be found elsewhere. It's a really good idea for an interesting plugin
Cheers
